"use client";
import { useEffect, useState } from "react";
import { site } from "@/content/site";
import { MobileMenu } from "./MobileMenu";
export function SiteHeader(){
 const [scrolled,setScrolled]=useState(false);const [menuOpen,setMenuOpen]=useState(false);const [active,setActive]=useState("#home");
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>80);onScroll();window.addEventListener("scroll",onScroll,{passive:true});const ids=site.nav.map(([,href])=>href.slice(1));const observer=new IntersectionObserver((entries)=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive("#"+visible.target.id);},{rootMargin:"-35% 0px -55%",threshold:[0,.2,.6]});ids.forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el);});return()=>{window.removeEventListener("scroll",onScroll);observer.disconnect();};},[]);
 const dark=!scrolled;
 return <><header className={"site-header sticky top-0 z-50 h-[72px] transition-colors md:h-[76px] "+(scrolled?"border-b border-line bg-white text-navy":"bg-transparent text-white")} style={{marginBottom:"-76px"}}><div className="container flex h-full items-center justify-between"><a href="#home" className="leading-none" aria-label="WoodRidge Real Estate home"><span className={"block font-serif text-[26px] "+(dark?"text-white":"text-navy")}>WoodRidge</span><span className="mt-1 block text-[9px] font-bold tracking-[.28em]">REAL ESTATE</span></a><nav aria-label="Primary navigation" className="hidden items-center gap-6 lg:flex">{site.nav.map(([label,href])=><a key={href} href={href} className={"relative py-6 text-[13px] font-bold "+(active===href?"after:absolute after:bottom-4 after:left-0 after:h-0.5 after:w-full after:bg-teal":"")}>{label}</a>)}</nav><a href="#appraisal" className="btn btn--primary hidden xl:inline-flex">Book a Free Appraisal</a><button type="button" onClick={()=>setMenuOpen(true)} className="flex min-h-11 min-w-11 flex-col items-center justify-center gap-1.5 lg:hidden" aria-label="Open menu" aria-expanded={menuOpen}><span className="h-px w-6 bg-current"/><span className="h-px w-6 bg-current"/><span className="h-px w-6 bg-current"/></button></div></header><MobileMenu open={menuOpen} onClose={()=>setMenuOpen(false)}/></>;
}
